---
- name: Ensure the VM volumes do not exist
  script: >
    destroy_virt_volume.sh
    {{ item.name }}
    {{ item.pool | default('default') }}
  with_items: "{{ volumes }}"
  when: not (item.prevent_destroy | default(false, true) | bool) # destory only if prevent_destroy flag is not set
  register: volume_result
  environment: "{{ libvirt_vm_script_env }}"
  changed_when:
    - volume_result is success
    - (volume_result.stdout | from_json).changed | default(True)
#  become: yes
